name: simple_bible
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  intl: ^0.19.0
  lottie: ^3.3.1
  objectbox: ^4.3.0
  # provider: ^6.1.5+1
  objectbox_flutter_libs: ^4.3.0
  path_provider: ^2.1.5
  responsive_sizer: ^3.3.1
  rich_text_controller: ^3.0.1
  scrollable_positioned_list: ^0.3.8
  uuid: ^4.5.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.15
  objectbox_generator: ^4.3.0
  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.6

flutter:
  uses-material-design: true

  assets:
    - asset/
    - asset/lotties/
    - asset/kjv.json
    - asset/AkuapemTwi.json
    
  fonts:
    - family: Myriad Pro
      fonts:
        # - asset: asset/Myriad Pro Semibold.ttf
        - asset: asset/Myriad Pro Light SemiExtended.otf
          weight: 400
    - family: Canterbury
      fonts:
        - asset: asset/Canterbury.ttf
          weight: 400